# Generated by Django 3.2.9 on 2021-12-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('country', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('transaction_type', models.CharField(max_length=50)),
                ('net', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('net_euro', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('vat_euro', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
